Switch back to ophasehq subdirectory in production
d120/pyophase pull request #447
Opened 2020-10-20 21:09 UTC by miterion

These seem to be the only locations this url is set but I will take a longer look later.

2020-10-23 10:44 UTC, ckleemann commented
I suggest to introduce a variable BASE_PATH etc. and use it as prefix for the other variables. BASE_PATH then can be used in the template. The website was introduced on 40b6041. The introduction only changed the variables mentioned. So the PR should work.

2020-10-23 10:45 UTC, ckleemann requested changes
I suggest to introduce a variable BASE_PATH etc. and use it as prefix for the other variables. BASE_PATH then can be used in the template.

2020-10-23 17:55 UTC, miterion commented
> I suggest to introduce a variable BASE_PATH etc. and use it as prefix for the other variables. BASE_PATH then can be used in the template.

I do not think that this could work with the current design. Since this template is an override of an `admin` template, it is not directly called by any of our views. This means it is not possible to easily inject a `BASE_PATH` variable into the view's context without using more complex methods like custom context processors or overriding view functions of the `admin` module.
Since we only change this setting every four years I would suggest to leave it in there. 

I added a `BASE_PATH` variable in 608ad63 but it is only used in the `settings_production.py`.

2020-10-24 07:51 UTC, ckleemann approved these changes

2020-10-24 07:52 UTC, merged